version: "3"

services:
  go-api-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    command: ["app"]

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: name
      MONGO_INITDB_ROOT_PASSWORD: passwords
    ports:
      - "27017:27017"
