version: "3"

services:
  go-api-server:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - "8080:8080"
    restart: always
    command: ["app"]

  postgres:
    build:
      context: ./database
      dockerfile: db.dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data

  redis:
    build:
      context: ./redis
      dockerfile: redis.dockerfile
    ports:
      - "6379:6379"

  fetcher:
    build:
      context: ./fetcher
      dockerfile: fetcher.dockerfile
