version: "3"

services:
  go-api-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    restart: always
    command: ["app"]

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwords
      POSTGRES_DB: API_DB
    ports:
      - "5432:5432"
