version: "3"

networks:
  docker-network:
    driver: bridge

services:
  go-api-server:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - "8080:8080"
    restart: always
    command: ["app"]
    networks:
      - docker-network

  postgres:
    build:
      context: ./database
      dockerfile: db.dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
    networks:
      - docker-network

  redis:
    build:
      context: ./redis
      dockerfile: redis.dockerfile
    networks:
      - docker-network

  fetcher:
    build:
      context: ./fetcher
      dockerfile: fetcher.dockerfile
    depends_on:
      - redis
    networks:
      - docker-network
